### PR TITLE
155 abstract syntax documentation

### PR DESCRIPTION
**Pull request by jbcaillau**

### CODE REVIEW

**Comment by jbcaillau** [comment]
Related issue: https://github.com/control-toolbox/CTDirect.jl/issues/69#issuecomment-2265593077

**Comment by jbcaillau** [comment]
@ocots BTW stupid trick to avoid duplicating `docs` when building the documentation locally (which needs to add the current package, contrary to what happens on runners):

```julia
julia> Pkg.add("OptimalControl"); include("make.jl"); Pkg.rm("OptimalControl")
```

If you're OK, I remove `_docs` from the repo.

**Comment by PierreMartinon** [comment]
@jbcaillau I guess you'll have to rename tutorial-nlp.md.foo back manually

**Comment by jbcaillau** [comment]
@PierreMartinon yes: local build (and draft PR) failing otherwise

**Comment by jbcaillau** [comment]
@ocots please review and merge

@PierreMartinon @gergaud do not hesitate to add further comments, examples to the [tutorial](https://control-toolbox.org/OptimalControl.jl/stable/tutorial-abstract.html)

**Comment by ocots** [comment]
@jbcaillau J'ai relu ton nouveau tuto. Top!

J'en ai profité pour restructurer. J'espère que ça ira pour toi. En gros, ça ne change aucun liens. C'est juste du point de vue du menu. On aura :

Capture d’écran 2024-08-04 à 23 10 00

**Pull request merged**
