### PR TITLE
move solve to OptimalControl

### PR DESCRIPTION
**Pull request by PierreMartinon**
Cf https://github.com/control-toolbox/CTDirect.jl/issues/175

- solve was moved to OptimalControl
- error message for missing extension (NLPModelsIpopt)
- some default parameters update

### CODE REVIEW

**Comment by PierreMartinon** [comment]
NB. tests cannot pass until the PR in CTDirect is merged and a new release done

**Comment by ocots** [comment]
> NB. tests cannot pass until the PR in CTDirect is merged and a new release done

Note that now `CTDirect.jl` is in the general registry. So it different now to make a new release.

**Comment by PierreMartinon** [comment]
So, we can merge when tests are ok with the latest CTdirect 0.9.5 from General, and the release tomorrow should be fine ?

**Comment by ocots** [comment]
`__time_grid_direct` not defined.

**Pull request merged**
