### PR TITLE
Add MadNLP to the nlp tutorial

### PR DESCRIPTION
**Pull request by jbcaillau**
@PierreMartinon can you please review and merge?

### CODE REVIEW

**Comment by ocots** [comment]
@PierreMartinon When reviewing, could you check if I set well the initial guess?

**Comment by PierreMartinon** [comment]
> @PierreMartinon When reviewing, could you check if I set well the initial guess?

I'll try to do this today !

**Comment by jbcaillau** [comment]
> > @PierreMartinon When reviewing, could you check if I set well the initial guess?
> 
> I'll try to do this today !

@ocots @PierreMartinon 
- initial guess set in the last call (Percival.jl)
- once merged, please release 0.10.1 to have doc on stable (including [abstract syntax](https://control-toolbox.org/OptimalControl.jl/dev/tutorial-abstract.html))

**Comment by PierreMartinon** [comment]
Manually building the docs seems to hang on my laptop, is it the same for you guys ?

My comments on the tutorial (I changed the text a bit while testing, and also added a separate test script `test-nlp.jl`, easier to work with than the doc page)
- noticed the duplicate solver calls (first one with #hide): here I got twice the ouptut anyway, so I kept only one. Was it supposed to change something ?
- concerning the 2 other solvers, Madnlp seems very similar to ipopt while Percival is slower. Default options for Percival may not be the best ones for us ?
- both options for warm start seem fine (you can check the starting guess by printing `nlp.meta.x0`). On this problem ipopt/madnlp converge in 2 iterations instead of 3 when using warm start :-)

**Review by PierreMartinon — APPROVED** [review]

**Comment by jbcaillau** [comment]
@PierreMartinon 
> Manually building the docs seems to hang on my laptop, is it the same for you guys ?

not really. but running on linux cluster (40 cores). Inria cluster, you can have access too.

> My comments on the tutorial (I changed the text a bit while testing, and also added a separate test script `test-nlp.jl`, easier to work with than the doc page)
> 
> * noticed the duplicate solver calls (first one with #hide): here I got twice the ouptut anyway, so I kept only one. Was it supposed to change something ?

real run time at second call as times are printed out both for Ipopt and MadNLP

> * concerning the 2 other solvers, Madnlp seems very similar to ipopt while Percival is slower. Default options for Percival may not be the best ones for us ?

Ipopt is the default and we should add MadNLP (https://github.com/control-toolbox/OptimalControl.jl/issues/259). Percival can be a user option through the retrieved `nlp`, not more I would say.

> * both options for warm start seem fine (you can check the starting guess by printing `nlp.meta.x0`). On this problem ipopt/madnlp converge in 2 iterations instead of 3 when using warm start :-)

👍🏽

**Pull request merged**
