### PR TITLE
build_solution

### PR DESCRIPTION
**Pull request by PierreMartinon**
Small update according to https://github.com/control-toolbox/CTDirect.jl/issues/115#issuecomment-2192171031
linked to the PR in CTDirect https://github.com/control-toolbox/CTDirect.jl/pull/154

Have a nice weekend !

### CODE REVIEW

**Comment by ocots** [comment]
It is written that `build_solution` is not found:

https://github.com/control-toolbox/OptimalControl.jl/actions/runs/9826313682/job/27127615878?pr=207#step:7:21

**Comment by PierreMartinon** [comment]
> It is written that `build_solution` is not found:
> 
> [control-toolbox/OptimalControl.jl/actions/runs/9826313682/job/27127615878?pr=207#step:7:21](https://github.com/control-toolbox/OptimalControl.jl/actions/runs/9826313682/job/27127615878?pr=207#step:7:21)

Yes, I haven't updated CTDirect yet, I wondered if it could interfere with the registration process. If not, I can do the release for CTDirect and you can relauch the tests here !

**Comment by ocots** [comment]
The process for registration is stopped at very early stage. No PR has been launched like for CTBase.jl. i think you can update and make a new release. I will update for the registration into yhe general registry.

**Comment by PierreMartinon** [comment]
> The process for registration is stopped at very early stage. No PR has been launched like for CTBase.jl. i think you can update and make a new release. I will update for the registration into yhe general registry.

Ok, 0.9.3 is out for CTDirect, doc builds now :-)
You can merge this one when ready.

**Pull request merged**
