### PR TITLE
Tuto - orbit transfer

### PR DESCRIPTION
**Pull request by jbcaillau**
adding orbit transfer tuto, check https://github.com/control-toolbox/OptimalControl.jl/issues/210

### CODE REVIEW

**Comment by ocots** [comment]
@jbcaillau Merge main before continuing. New applications in the `make.jl`.

**Comment by ocots** [comment]
@jbcaillau Still first commit?

**Comment by ocots** [comment]
Tell when it is finished. I will make a new release to have the doc in stable.

**Review by jbcaillau — COMMENTED** [review]
@ocots I am leaving `_docs` now, need to be removed *later*

**Pull request merged**
