### PR TITLE
docs and CTDirect update

### PR DESCRIPTION
**Pull request by BaptisteCbl**
I updated the doc and modified a little bit the solve to match the new version of CTDirect.

### CODE REVIEW

**Comment by ocots** [comment]
Thanks @BaptisteCbl !

**Comment by ocots** [comment]
@jbcaillau a new release of OptimalControl is available: v0.7.0.

For the doc, it will be updated first here: https://control-toolbox.org/OptimalControl.jl/stable/

Then, I will make the update where all the docs are aggregated: https://control-toolbox.org/CTDocs.jl/optimalcontrol/stable/

If you want to update the doc, feel free!

**Comment by ocots** [comment]
Then, when we will have some results on the new perfs, we could thank Tangi!

**Comment by jbcaillau** [comment]
I'm on it.

PS. Still some old `@Poisson` in `examples/goddard.jl` from `OptimalControl`. Having a look at it, too.

**Pull request merged**
