### PR TITLE
Examples

### PR DESCRIPTION
**Pull request by jbcaillau**
@ocots please check unified versions of examples (no more notebooks, single version for `basic.jl` and `goddard`) and merge

### CODE REVIEW

**Comment by ocots** [comment]
Are you ok if I put the jl files into the doc?

I need a new release of ctdirect then I will do a new release of OC without direct shooting and if you are ok I will put the examples into the doc.

**Comment by jbcaillau** [comment]
Sure, but then wouldn't it be better to have `md` files (for `Documenter.jl`) instead of `jl` ones? I actually hesitated but wanted to put forward the possibility to run the code directly. And this kind of `jl` file that includes markdown docstrings is well rendered on, *e.g.*, `Pluto` [^1] (or using some `vscode` extensions...)

[^1]: https://juliahub.com/ui/Notebooks/cadojo/Astrodynamics?type=packages

> Are you ok if I put the jl files into the doc?
> 
> I need a new release of ctdirect then I will do a new release of OC without direct shooting and if you are ok I will put the examples into the doc.

**Comment by ocots** [comment]
To put them on the doc, I will have to change them to md files. This seems the most usual to do for the moment. The jl files are for concrete applications. Not doc.

**Comment by jbcaillau** [comment]
Right now I need to have them running (`Documenter.jl` will also run them but well...) So please keep them as `jl` files and merge. See also [this post](https://github.com/orgs/control-toolbox/discussions/22#discussioncomment-5541700)

**Comment by ocots** [comment]
I do it by the end of the week.

**Pull request merged**
